# VERSION DE DOCKER-COMPOSE
version: '3'
# . ES PARA CONSTRUIR DESDE DONDE ESTA ESTE ARCHIVO CREADO
services:
  web:
    container_name: api-restaurante-db 
    restart: always
    build: .
    ports:
      - 4000:4010
    links: 
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: restaurante-db
    image: mongo
    ports:
      - 27018:27017